# =============================================================================
# Test App — Source Namespace (quay)
# Pulls busybox image from SOURCE Quay registry
# Used to verify source Quay is serving images correctly
# =============================================================================
apiVersion: v1
kind: Namespace
metadata:
  name: test-app
spec: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-app-pvc
  namespace: test-app
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ocs-storagecluster-ceph-rbd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app-deploy
  namespace: test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: test-app-container
        image: quay-registry-quay-quay.apps.kasten-se-lab-baremetal.kasten.veeam.local/praveen/busybox
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "while true; do sleep 3600; done"]
        volumeMounts:
        - mountPath: /data
          name: data
      imagePullSecrets:
      - name: quay-pull-secret
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: test-app-pvc
